language: android
sudo: false

cache:
  directories:
  - $HOME/.gradle/caches/

android:
  components:
    - platform-tools
    - tools
    - build-tools-19.1.0
    - android-19

    # - sys-img-armeabi-v7a-android-19

before_script:
  - chmod +x gradlew

script:
  - ./gradlew assembleDebug --stacktrace

deploy:
  provider: releases
  api-key: $GITHUB_APIKEY
  file: "app/build/outputs/apk/app-debug-unaligned.apk"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true